export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCTS_DETAIL_REQUEST = "GET_PRODUCTS_DETAIL_REQUEST";
export const GET_PRODUCTS_DETAIL_SUCCESS = "GET_PRODUCTS_DETAIL_SUCCESS";
export const GET_PRODUCTS_DETAIL_FAIL = "GET_PRODUCTS_DETAIL_FAIL";
export const GET_PRODUCTS_DETAIL_RESET = "GET_PRODUCTS_DETAIL_RESET";
